MD007:
  indent: 4
  start_indented: false

MD013:
  line_length: 200
  heading_line_length: 80
  code_block_line_length: 200
  code_blocks: true
  tables: true
  headings: true
  headers: true
  strict: false
  stern: false

MD012:
  maximum: 20